settings:
  error-permission: '&x&f&b&4&d&0&0[⚠] Ошибка! &fУ вас недостаточно прав!'
  error-sound: "ENTITY_VILLAGER_NO" # список звуков можно найти по команде /playsound тут можно нажать TAB block ник
  no-sound: "&x&f&b&4&d&0&0[⚠] Ошибка! &fВ конфиге неверный звук!!!" # список звуков можно найти по команде /playsound тут можно нажать TAB block ник
  console: '&x&f&b&4&d&0&0[⚠] Ошибка! &fДанная команда может быть выполнена только от имени игрока!'
  no-one-around: '&6[✇]&e Радар &f› Вокруг вас никого нет'
  radar: '&6【 ⓘ 】&e Радар &f› Игроки в радиусе &6{search_radius} блоков&f от вас:'
  max-radius: 100