name: bNear
version: 2.0
main: ru.mine.bnear.BNear
author: [ bTeam]
description: bNear— Это приятный плагин на /near. Плагин имеет настройку радиуса звуков и многое другое, а также есть кнопка, открывающая инвентарь игрока. которого нашёл near.
softdepend:
  - LuckPerms
  - PlaceholderAPI
commands:
  near:
    aliases: [bnear]