name: bNear
version: 1.0
main: ru.mine.bnear.BNear
api-version: '1.17'
author: [ BaNoF_, Lairon1]
description: Это мой первый плагин для SpigotMc.ru. Надеюсь, вам понравится. Часть кода взял из гита Lairon1. Спасибо ему!
softdepend:
  - LuckPerms
commands:
  near:
    aliases: [bnear]